# Get editor completions based on the config shcema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
(#fc3d67)$time\
[î‚°](bg:#ff823e fg:#fc3d67)\ 
$git_branch\
$git_status\
[î‚°](fg:#ff823e bg:#C274DD)\
[î‚°](fg:#C274DD bg:#7702A0)\
[î‚°](fg:#7702A0 bg:#9A348e)\
$username\
$hostname\
[î‚°](fg:#9A348e bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$directory[î‚° ](fg:#33658A)"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
#style_user = "bg:#fc3d67"
style_user = "bg:#9A348e"
style_root = "bg:#e41c3f"
format = '[ $user ]($style)'

[hostname]
ssh_only = true
ssh_symbol = "ï„ˆ "
#style = "bg:#fc3d67"
style = "bg:#9A348e"
format = '[$ssh_symbol$hostname]($style)'
trim_at = "."
disabled = false


[directory]
style = "bg:#33658A"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "â€¦/"

## Here is how you can shorten some long paths by text replacement
## similar to mapped_locations in Oh My Posh:

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
#"Music" = "ï€ "
"Pictures" = "ï€¾ "
## Keep in mind that the order matters. For example:
## "Important Documents" = " ïœ˜ï„ª "
## will not be replaced, because "Documents" was already substituted before.
## So either put "Important Documents" before "Documents" or use the substituted version:
## "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïˆš" 
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "ïƒƒ"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "ï†»"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï‚› "
always_show_remote = true
style = "bg:#ff823e"
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸ"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "???"
stashed = "ğŸ“¦"
staged = '[++\($count\)](green)'
renamed = "NUFN"
deleted = "ğŸ—‘"

style = "bg:#ff823e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "Î»" 
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "ïƒ´ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "ï‡Œ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
#style = "bg:#9A348E"
style = "bg:#fc3d67"
format = '[ î¯† $time ]($style)'

